version: '3'

services:
  frontend:
    build: ./frontend/savings-account
    restart: unless-stopped
    container_name: frontend
    ports:
    - 80:80
    - 443:443
    depends_on:
    - backend
    networks:
    - lan

  backend:
    build: ./backend/savings-account
    restart: unless-stopped
    container_name: backend
    ports:
    - 8080:8080
    environment:
    - MYSQL_HOST=mariadb
    - MYSQL_DATABASE=db
    - MYSQL_USER=pifou
    - MYSQL_PASSWORD=pasglop
    depends_on:
    - mariadb
    networks:
    - lan

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
    - data:/var/lib/mysql
    - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql
    - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
    - MYSQL_ROOT_PASSWORD=glopglop
    - MYSQL_DATABASE=db
    - MYSQL_USER=pifou
    - MYSQL_PASSWORD=pasglop
    networks:
    - lan

networks:
  lan:

volumes:
  data:
